# Generated by Django 4.1 on 2022-12-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_image', models.ImageField(upload_to='')),
                ('product_price', models.IntegerField()),
                ('product_offerprice', models.IntegerField()),
                ('product_description', models.TextField(max_length=500)),
            ],
        ),
    ]
