# Generated by Django 4.1 on 2022-12-21 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Furnitur',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
