# Generated by Django 4.1 on 2022-12-21 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0005_delete_furnitur_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_image', models.ImageField(upload_to='')),
                ('product_price', models.IntegerField()),
                ('product_offerprice', models.IntegerField()),
                ('product_description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Furnitur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_measurment', models.TextField(max_length=100)),
                ('product_small', models.TextField(max_length=100)),
                ('product_large', models.TextField(max_length=100)),
                ('product_warrenty', models.TextField(max_length=100)),
                ('product_brand', models.CharField(max_length=100)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
    ]
