# Generated by Django 4.1 on 2022-12-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=500)),
                ('phone_number', models.IntegerField()),
                ('alternative_number', models.IntegerField()),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('landmark', models.TextField()),
                ('house_no', models.TextField()),
                ('email', models.TextField()),
            ],
        ),
    ]
