# Generated by Django 4.1 on 2023-02-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='product_image',
            field=models.ImageField(upload_to='furniture'),
        ),
    ]
